### ISSUE TITLE
StockQuote and StockChart are not working. 

### ISSUE THREAD

**Issue by anmolgupta-aeologic** [sarveshbhatnagar/yahoofin#12]

**Comment by sarveshbhatnagar** [comment]
Can you please elaborate? It seems to be working fine for me... Can you tell me how you are using it? For reference on how to use them, please look at tests, I will update example file soon.

**Comment by sarveshbhatnagar** [comment]
Please check https://github.com/sarveshbhatnagar/yahoofin/blob/main/test/yahoofin_test.dart for a sample run or how to call methods. I will soon be adding an example file for the same. Thank you.
