### ISSUE TITLE
Unknown Class 'StockQuote'

### ISSUE THREAD

**Issue by viewasia** [sarveshbhatnagar/yahoofin#16]
1. Ran Command  - flutter pub add yahoofin & dependencies added to the pubspec.yaml correctly
2. In Dart code used 'package: yahoofin/yahoofin.dart';
3. Wrote the following code:
   final yfin = YahooFin();
   StockInfo info = yfin.getStockInfo(ticker: "msft");
   StockQuote price = yfin.getPrice(stockInfo: info);

Get error : Undefined class 'StockQuote'

Using Android Studio Artic Fox 2020.3.1 Patch 2 on Mac OS Big Sur 11.5.2, Dart SDK Version 2.15.0-02.0 dev, flutter 2.6.0-1.0.pre.189

**Comment by sarveshbhatnagar** [comment]
Hello, Thank you for this bug report and contribution! I think the issue should be solved now.
